src/Entity/NewsHistory.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsHistoryRepository")
 */
class NewsHistory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $news_id;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $category_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $author_id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $edited_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNewsId(): ?int
    {
        return $this->news_id;
    }

    public function setNewsId(int $news_id): self
    {
        $this->news_id = $news_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeInterface
    {
        return $this->edited_at;
    }

    public function setEditedAt(?\DateTimeInterface $edited_at): self
    {
        $this->edited_at = $edited_at;

        return $this;
    }
}

templates/inc/article_list.html.twig
<article class="artykul">


    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="row">

            <div class="col-10">
                {% if one_news.isDelete %}
                <span class="badge badge-danger text-wrap p-2">Usunięto</span>
                {% endif %}
                <a class="artykul_title" href="{{ path('news_show', {'id': one_news.id}) }}">
                    {{ one_news.title }}</a>

                <div class="artykul_author">opublikowano
                    {{ one_news.PublishedAt|date("d/m/Y H:i:s") }} przez
                    {{ one_news.author.username }}{% if one_news.editedAt %} | Edytowano {{ one_news.editedAt|date("d/m/Y H:i:s") }}{% endif %}



                    <br>
                </div>
            </div>

            <div class="col text-center">

                <span class="badge badge-primary text-wrap p-3">
                            {{ one_news.category }}
                </span>




            </div>
        </div>



    </div>


</article>

templates/inc/navbar.html.twig
<header>

    <nav class="navbar navbar-expand-xl navbar-custom py-0 border-bottom-blue">

        <a class="navbar-brand" href="{{ path('home') }}">Anczeje</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_menu" aria-controls="main_menu" aria-expandend="false" aria-label="Przełącznik nawigacji">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="main_menu">


            <ul class="navbar-nav mr-auto">

                <li class="nav-item"><a class="nav-link" href="{{ path('home') }}">Strona główna</a></li>

                {% if is_granted('ROLE_USERB') %}

                <li class="nav-item"><a class="nav-link" href="{{ path('news_by_cat', {'category': 'Książki'}) }}">Książki</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ path('news_by_cat', {'category': 'Zadania'}) }}">Zadania</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ path('news_by_cat', {'category': 'Sieci'}) }}">Sieci</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ path('news_by_cat', {'category': 'CPP'}) }}">C++</a></li>

                <li class="nav-item"><a class="nav-link" href="{{ path('news_add') }}">Dodaj artykuł</a></li>
                <li class="nav-item"><a class="nav-link" href="upload.php">Dodaj plik</a></li>


                <!--

                <li class="nav-item"><a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Wycieki sprawdzianów</a></li>
-->


                {% endif %}

            </ul>

            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <a class="btn btn-primary mb-1 mr-2" href="{{ path('profile') }}" role="button">Twój profil - {{ app.user.username }}</a></li>
                <a class="btn btn-success mb-1" href="{{ path('app_logout') }}" role="button">Wyloguj</a></li>
            {% endif %}
        </div>
    </nav>


</header>